replace cjson with json-c
* debug.h: Rename to powerd_debug.h
  json-c is also staging debug.h and wrong one is used in builds where
  json-c is used instead of cjson.

  json-c include paths appear before include/internal and build fails
  with:
    powerd/4.0.0-25-r3/git/libpowerd/wait.c:126: undefined reference to
      `TRACE'
    collect2: error: ld returned 1 exit status

Change-Id: I2681bc0c50ecb3dd4ef97070ae4df434a0cf0a76
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>